
<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\tModLoader.targets" />
  <PropertyGroup>
    <AssemblyName>SpikersArchipelago</AssemblyName>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
  </ItemGroup>
  <ItemGroup>
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Archipelago.MultiClient.Net">
      <HintPath>lib\Archipelago.MultiClient.Net.dll</HintPath>
    </Reference>
    <Reference Include="CalamityMod">
      <HintPath>ref\CalamityMod.dll</HintPath>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>lib\Newtonsoft.Json.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>